In [1]:
import logging

import shap

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)
shap.initjs()

In [2]:
from darts.datasets import AirPassengersDataset
from darts.explainability import TorchExplainer
from darts.models import NLinearModel

series = AirPassengersDataset().load().astype("float32")
model = NLinearModel(
    input_chunk_length=13,
    output_chunk_length=12,
    n_epochs=10,
)
model.fit(series[:-36])
shap_explain = TorchExplainer(model)

INFO:darts.models.forecasting.torch_forecasting_model:Train dataset contains 84 samples.
INFO:darts.models.forecasting.torch_forecasting_model:Time series values are 32-bits; casting model to float32.
INFO: GPU available: True (mps), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (mps), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO:lightning.pytorch.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | layer           | Linear           | 168    | train
-------------------------------------------------------------
168       Trainable params
0         Non-trainable params
168       Total params
0.001     Total estimated model params size (MB)
6         Modules in train mode
0         Modules in eval mode
/Users/engs2902/Documents/code/darts/.venv/lib/python3.13/site-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
/Users/engs2902/Documents/code/darts/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Training: |          | 0/? [00:00<?, ?it/s]

INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.
/Users/engs2902/Documents/code/darts/darts/utils/statistics.py:489: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  return kpss(ts.values(copy=False), regression, nlags)
WARNING:darts.explainability.utils:At least component '#Passengers' of target series at index 0 is not stationary. Beware of wrong interpretation of the chosen explainability.

Background X shape: torch.Size([96, 13])

In [3]:
results = shap_explain.explain()

/Users/engs2902/Documents/code/darts/darts/utils/statistics.py:489: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is smaller than the p-value returned.

  return kpss(ts.values(copy=False), regression, nlags)
WARNING:darts.explainability.utils:At least component '#Passengers' of target series at index 0 is not stationary. Beware of wrong interpretation of the chosen explainability.

Foreground X shape: torch.Size([96, 13])
Prediction times: DatetimeIndex(['1950-02-01', '1950-03-01', '1950-04-01', '1950-05-01',
               '1950-06-01', '1950-07-01', '1950-08-01', '1950-09-01',
               '1950-10-01', '1950-11-01', '1950-12-01', '1951-01-01',
               '1951-02-01', '1951-03-01', '1951-04-01', '1951-05-01',
               '1951-06-01', '1951-07-01', '1951-08-01', '1951-09-01',
               '1951-10-01', '1951-11-01', '1951-12-01', '1952-01-01',
               '1952-02-01', '1952-03-01', '1952-04-01', '1952-05-01',
               '1952-06-01', '1952-07-01', '1952-08-01', '1952-09-01',
               '1952-10-01', '1952-11-01', '1952-12-01', '1953-01-01',
               '1953-02-01', '1953-03-01', '1953-04-01', '1953-05-01',
               '1953-06-01', '1953-07-01', '1953-08-01', '1953-09-01',
               '1953-10-01', '1953-11-01', '1953-12-01', '1954-01-01',
               '1954-02-01', '1954-03-01', '1954-04-01', '1954-05-01',
               '1954-06-01', '1954-07-01', '1954-08-01', '1954-09-01',
               '1954-10-01', '1954-11-01', '1954-12-01', '1955-01-01',
               '1955-02-01', '1955-03-01', '1955-04-01', '1955-05-01',
               '1955-06-01', '1955-07-01', '1955-08-01', '1955-09-01',
               '1955-10-01', '1955-11-01', '1955-12-01', '1956-01-01',
               '1956-02-01', '1956-03-01', '1956-04-01', '1956-05-01',
               '1956-06-01', '1956-07-01', '1956-08-01', '1956-09-01',
               '1956-10-01', '1956-11-01', '1956-12-01', '1957-01-01',
               '1957-02-01', '1957-03-01', '1957-04-01', '1957-05-01',
               '1957-06-01', '1957-07-01', '1957-08-01', '1957-09-01',
               '1957-10-01', '1957-11-01', '1957-12-01', '1958-01-01'],
              dtype='datetime64[us]', freq=None)

  0%|          | 0/96 [00:00<?, ?it/s]

INFO:shap:num_full_subsets = 3
INFO:shap:remaining_weight_vector = array([0.3626943 , 0.32642487, 0.31088083])
INFO:shap:num_paired_subset_sizes = 6
INFO:shap:weight_left = np.float64(0.32084025993652715)
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -5.9644756 ,  -6.61383267,  -5.85083935,  -6.10765656,
        -6.4851363 ,   0.        ,   0.        ,   0.        ,
        -6.08569291,  -7.10901352,  -7.78326039,  -7.21064925,
       -52.42679718])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -6.01202649,  -6.94762078,  -9.34476474,  -8.45750901,
        -7.14915402,   0.        ,   0.        ,   0.        ,
        -6.23955903,  -7.17292893,  -7.75818623,  -7.25087802,
       -42.07978977])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -6.14843183,   0.        ,  -9.90659058, -10.88743862,
       -11.98510566,  -8.20996335,   0.        ,   0.        ,
        -6.59711684,  -7.32709487,  -8.11278414,  -7.32486263,
       -28.19373514])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,   0.        , -11.08206412,
       -12.24217162, -10.37393393,  -8.72567755,  -8.05994566,
        -8.04000674,  -8.76840132, -10.26906133,  -8.53143639,
       -15.91993403])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,   0.        ,  -8.41440809,
       -11.84919097, -10.51509038,  -9.47566021,  -9.55266486,
       -10.05758787,  -9.90130691, -10.04242188,  -8.76316567,
       -12.8983057 ])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -6.46019797,   0.        ,   0.        ,   0.        ,
        -9.39375542, -10.52655947,  -9.83225866,  -9.83767707,
       -11.28746305, -11.92275771, -10.55935   ,  -8.42274668,
       -14.06889132])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -6.46808002,   0.        ,   0.        ,   0.        ,
        -7.07523331,  -9.1599722 ,  -9.78811882,  -9.9193616 ,
       -11.6428486 , -13.29512625, -14.66391671, -10.13263117,
       -11.25539631])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -6.47014645,   0.        ,   0.        ,   0.        ,
        -6.60074428,  -6.56434577,  -8.86637376,  -9.64145529,
       -11.62155974, -13.38354855, -15.00252674, -13.10079121,
       -14.01431774])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -6.17623916,  -6.14047322,   0.        ,   0.        ,
        -6.31038384,  -6.05354581,   0.        ,  -7.89942687,
       -11.24590575, -13.48257089, -15.1756162 , -13.85105467,
       -22.18384458])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -6.09718759,  -6.07042138,   0.        ,  -5.50908679,
        -6.28039959,  -5.59889442,   0.        ,   0.        ,
        -7.56845971, -12.76767203, -15.30126429, -13.8578607 ,
       -32.28799754])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -6.09458345,  -6.07500555,   0.        ,  -5.53475154,
        -6.30713401,  -5.57781237,   0.        ,   0.        ,
        -6.21736663,  -7.83316664, -10.84631743, -13.15270671,
       -44.4263974 ])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -6.09572938,  -6.08805021,   0.        ,  -5.5582177 ,
        -6.32955426,  -5.55684242,   0.        ,   0.        ,
        -6.07078692,  -7.27269362,  -8.18021485,  -7.52462744,
       -53.5905408 ])
INFO:shap:num_full_subsets = 3
INFO:shap:remaining_weight_vector = array([0.3626943 , 0.32642487, 0.31088083])
INFO:shap:num_paired_subset_sizes = 6
INFO:shap:weight_left = np.float64(0.32084025993652715)
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -5.78087051,  -5.81142933,  -6.00209659,  -6.44829066,
         0.        ,   0.        ,   0.        ,  -6.04402113,
        -7.00348836,  -7.70685137,  -7.15217614,  -7.22444101,
       -47.90350033])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,  -6.16727691,  -9.65806929,  -8.92052978,
        -6.23960813,   0.        ,   0.        ,  -6.04677431,
        -7.09107913,  -7.49795353,  -7.36757307,  -7.18993634,
       -38.74987478])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        , -10.07705082, -11.7989126 ,
       -10.1969798 ,  -6.96914569,   0.        ,  -6.49915055,
        -7.30776432,  -8.01355562,  -7.62308423,  -7.40420572,
       -26.04810157])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,   0.        , -11.89109864,
       -10.56096256,  -8.82216509,  -8.78122575,  -8.97496174,
        -8.74331698,  -9.47087293,  -9.19531405,  -8.89195513,
       -14.95329704])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,   0.        ,  -8.9740898 ,
       -10.20118254,  -8.93067644,  -9.55496754, -10.65316531,
       -11.17606652, -10.82114898,  -9.00921969,  -9.05578932,
       -12.14066894])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,   0.        ,  -6.28664372,
        -8.17819424,  -8.73372008,  -9.78654945, -11.18221467,
       -12.73929393, -13.48642551,  -9.77882795,  -8.64663352,
       -13.08704923])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,   0.        ,  -6.25902972,
        -6.1830481 ,  -7.5690979 ,  -9.74499171, -11.27971552,
       -13.15622579, -15.03440617, -13.46141516, -10.405013  ,
       -10.51876334])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -5.78903619,   0.        ,   0.        ,  -6.14630322,
        -5.60076878,   0.        ,  -8.83795492, -11.02000659,
       -13.22184195, -15.1059065 , -13.64830125, -13.51724278,
       -12.80816538])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -5.69487516,   0.        ,  -5.42921067,  -6.01148159,
        -5.452269  ,   0.        ,   0.        ,  -9.11722666,
       -12.83337738, -14.97962664, -13.96171077, -14.08442188,
       -20.50518475])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -5.64497025,   0.        ,  -5.4206588 ,  -5.98676331,
        -5.36585672,   0.        ,   0.        ,  -6.15782673,
        -8.60121472, -13.92545042, -13.87834695, -14.22059453,
       -29.74603636])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -5.65523528,   0.        ,  -5.44655467,  -6.02756732,
        -5.402787  ,   0.        ,   0.        ,  -5.97783613,
        -7.03134419,  -8.38546404,  -9.895722  , -13.51141587,
       -40.86273155])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -5.65586836,   0.        ,  -5.45565812,  -6.05288175,
        -5.42214764,   0.        ,   0.        ,  -5.96227179,
        -6.85887495,  -7.75484212,  -7.50389508,  -7.74647729,
       -49.24438568])
INFO:shap:num_full_subsets = 3
INFO:shap:remaining_weight_vector = array([0.3626943 , 0.32642487, 0.31088083])
INFO:shap:num_paired_subset_sizes = 6
INFO:shap:weight_left = np.float64(0.32084025993652715)
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,  -5.80312643,  -6.408636  ,  -5.54070118,
         0.        ,   0.        ,  -5.75727613,  -6.40805534,
        -7.49379344,  -7.10541622,  -7.38710608,  -6.85800496,
       -41.98536826])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,  -6.11680112, -10.36611961,  -7.74109995,
         0.        ,   0.        ,  -5.99436024,  -6.54707408,
        -7.70071276,  -7.19286414,  -7.41456319,  -6.92050801,
       -33.75686829])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        , -10.91056096, -10.37578099,
        -9.06462107,  -6.85725373,   0.        ,  -7.26739333,
        -8.26087731,  -7.29522284,  -7.44345552,  -7.35434737,
       -22.80251434])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,   0.        , -10.58366747,
        -9.0007272 ,  -9.17135789,  -9.51469249, -10.22660179,
        -9.92898646,  -8.37939834,  -9.37471757,  -8.27305008,
       -13.40672343])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,   0.        ,  -8.03572885,
        -8.67885372,  -9.20019833, -10.41184195, -12.235925  ,
       -12.66453679,  -9.57372037,  -9.16192596,  -8.47065231,
       -10.88829457])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,  -5.98865553,   0.        ,
        -6.97136114,  -8.77002589, -10.5310231 , -12.95581197,
       -14.30520835, -12.11553641,  -9.98420734,  -8.24374163,
       -11.49483782])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,  -5.61683324,  -5.87214347,   0.        ,
         0.        ,  -7.50550494, -10.89463666, -12.96459493,
       -14.60455949, -13.50900715, -13.79275563,  -9.71130975,
        -9.07139906])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,  -5.85035331,  -5.5187579 ,
         0.        ,  -5.24165918,  -9.60322881, -12.43484061,
       -14.76339842, -13.32951709, -14.11118779, -12.512711  ,
       -11.52812327])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,  -5.27303213,  -5.78301081,  -5.21212514,
         0.        ,   0.        ,  -6.12388448, -10.0378981 ,
       -14.17217169, -13.62582552, -14.17283433, -13.06461557,
       -17.9688549 ])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,  -5.26721003,  -5.80812815,  -5.21639159,
         0.        ,   0.        ,  -5.72080839,  -6.59156249,
        -9.4239716 , -12.69153999, -14.1216293 , -13.21092075,
       -26.06389145])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,  -5.28881544,  -5.8404221 ,  -5.25568476,
         0.        ,   0.        ,  -5.70160592,  -6.38398638,
        -7.65473253,  -7.73620166, -10.04666897, -12.56790622,
       -35.77123985])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,  -5.3025907 ,  -5.85220865,  -5.27951563,
         0.        ,   0.        ,  -5.68419292,  -6.36901943,
        -7.46281119,  -7.17211435,  -7.59918347,  -7.30578898,
       -43.0890068 ])
INFO:shap:num_full_subsets = 3
INFO:shap:remaining_weight_vector = array([0.3626943 , 0.32642487, 0.31088083])
INFO:shap:num_paired_subset_sizes = 6
INFO:shap:weight_left = np.float64(0.32084025993652715)
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0)
INFO:shap:phi = array([  0.        ,  -6.06326118,  -5.56565728,   0.        ,
         0.        ,  -5.72847912,  -6.57064431,  -7.24833061,
        -6.91897194,  -7.15308992,  -7.1550958 ,  -5.92442065,
       -44.30551956])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0)
INFO:shap:phi = array([  0.        ,  -6.57961342,  -9.16071237,  -6.80258283,
         0.        ,   0.        ,  -6.61221802,  -7.73553766,
        -7.12525388,  -7.20736871,  -7.05194623,  -6.2809403 ,
       -35.79872559])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0)
INFO:shap:phi = array([  0.        ,   0.        ,  -9.4972587 ,  -8.56150694,
        -8.81843097,  -8.11723288,  -8.06835486,  -8.0816442 ,
        -7.52732201,  -7.76500304,  -6.93122012,   0.        ,
       -24.18916362])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0)
INFO:shap:phi = array([  0.        ,   0.        ,   0.        ,  -8.60976204,
        -9.07125031, -10.34096708, -11.33798359, -11.18441404,
        -8.89961944,  -8.96689184,  -8.44524882,  -7.44297726,
       -14.08639728])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0)
INFO:shap:phi = array([  0.        ,   0.        ,   0.        ,  -6.49261122,
        -8.7666916 , -10.46388252, -12.4713684 , -13.52181659,
       -11.35878261, -10.14735043,  -8.27119433,  -7.58240979,
       -11.44617767])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0)
INFO:shap:phi = array([  0.        ,  -5.63059971,   0.        ,   0.        ,
        -6.9626948 , -10.15661836, -12.54972319, -14.20974222,
       -12.86262801, -12.34452236,  -9.26452759,  -6.93299931,
       -12.0308263 ])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0)
INFO:shap:phi = array([  0.        ,  -5.66788038,   0.        ,   0.        ,
        -5.25944821,  -8.80398741, -12.48077351, -14.329741  ,
       -13.276997  , -13.76063296, -12.6979936 ,  -8.3255181 ,
        -9.65579846])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0)
INFO:shap:phi = array([ -5.18703848,  -5.56060435,   0.        ,   0.        ,
         0.        ,  -6.16469003, -11.26776487, -13.94326335,
       -13.20222527, -13.85343997, -13.04718727, -10.63572935,
       -11.89147646])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0)
INFO:shap:phi = array([ -5.13954369,  -5.49494393,   0.        ,   0.        ,
         0.        ,  -5.56352655,  -7.04188058, -11.44575577,
       -12.77859707, -13.89911818, -13.20456912, -11.22487064,
       -18.81252104])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0)
INFO:shap:phi = array([ -5.12643299,  -5.49897921,   0.        ,   0.        ,
         0.        ,  -5.51001203,  -6.57796641,  -7.54706568,
        -8.54900439, -12.95286893, -13.16776749, -11.36096144,
       -27.39004338])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0)
INFO:shap:phi = array([ -5.14468969,  -5.52613673,   0.        ,   0.        ,
         0.        ,  -5.51042482,  -6.55911975,  -7.31646368,
        -6.97583834,  -7.87949011,  -9.46029529, -10.80552233,
       -37.66794643])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0)
INFO:shap:phi = array([ -5.15104098,  -5.54448609,   0.        ,   0.        ,
         0.        ,  -5.4969228 ,  -6.54225543,  -7.30321829,
        -6.80932686,  -7.30675779,  -7.23472717,  -6.22948719,
       -45.41646816])
INFO:shap:num_full_subsets = 3
INFO:shap:remaining_weight_vector = array([0.3626943 , 0.32642487, 0.31088083])
INFO:shap:num_paired_subset_sizes = 6
INFO:shap:weight_left = np.float64(0.32084025993652715)
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -5.84098235,   0.        ,   0.        ,   0.        ,
        -5.16660863,  -6.34672452,  -7.43313338,  -6.99868073,
        -7.02492616,  -6.62033744,  -6.17839189,  -6.32060701,
       -48.2611532 ])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,  -8.06051792,  -7.02825379,
        -6.27263854,  -6.86726987,  -7.56228386,  -6.89510081,
        -7.49977417,  -6.79239725,   0.        ,  -6.48029873,
       -39.23587213])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,  -8.20087084,  -8.94956566,
        -9.99606602,  -9.10177839,  -8.70628607,  -7.30099458,
        -7.74961145,  -6.940203  ,   0.        ,  -6.56035973,
       -26.31612632])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,   0.        ,  -8.71316455,
       -10.13788119, -11.73869868, -12.48812611, -10.36195702,
        -9.33071973,  -7.88147399,  -7.39665904,  -7.50002522,
       -14.91958513])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([  0.        ,   0.        ,   0.        ,  -6.61645419,
        -9.85136756, -11.95567419, -13.80452005, -12.40888304,
       -11.83418667,  -9.01261369,  -7.2366609 ,  -7.69278026,
       -12.10394898])
INFO:shap:np.sum(w_aug) = np.float64(12.999999999999996)
INFO:shap:np.sum(self.kernelWeights) = np.float64(1.0000000000000002)
INFO:shap:phi = array([ -5.65701383,   0.        ,   0.        ,   0.        ,
        -7.49451101, -11.61863783, -14.12692356, -13.02648973,
       -13.05769835, -11.1812582 ,  -8.05480163,  -7.28277496,
       -12.90452004])

shap_explanation_tmp.values.shape: (96, 13, 12)
shap_explanation_tmp.data.shape: (96, 13)
shap_explanation_tmp.base_values.shape: (96, 12)

In [4]:
results.get_explanation(horizon=1)

                    0         1         2         3         4  ...          8          9         10         11         12
1950-02-01  -5.964476 -6.613833 -5.850839 -6.107657 -6.485136  ...  -6.085693  -7.109014  -7.783260  -7.210649 -52.426797
1950-03-01  -5.780871 -5.811429 -6.002097 -6.448291  0.000000  ...  -7.003488  -7.706851  -7.152176  -7.224441 -47.903500
1950-04-01   0.000000 -5.803126 -6.408636 -5.540701  0.000000  ...  -7.493793  -7.105416  -7.387106  -6.858005 -41.985368
1950-05-01   0.000000 -6.063261 -5.565657  0.000000  0.000000  ...  -6.918972  -7.153090  -7.155096  -5.924421 -44.305520
1950-06-01  -5.840982  0.000000  0.000000  0.000000 -5.166609  ...  -7.024926  -6.620337  -6.178392  -6.320607 -48.261153
...               ...       ...       ...       ...       ...  ...        ...        ...        ...        ...        ...
1957-09-01  10.279322  8.492411  5.821125  0.000000  0.000000  ...   6.612270   6.899761  10.098769  11.830520  89.500660
1957-10-01   8.078462  6.122604  0.000000  0.000000  5.694489  ...   6.877478  10.074966  12.186904  12.031812  64.294962
1957-11-01   0.000000  0.000000  6.074746  6.094612  0.000000  ...  10.395049  12.125212  12.176716   9.009047  42.056800
1957-12-01   0.000000  0.000000  6.364467  0.000000  7.877893  ...  12.896265  12.469866   9.027877   6.364653  25.456608
1958-01-01   0.000000  6.646312  0.000000  8.521128  7.648050  ...  12.544536   9.524325   6.190075   0.000000  37.775730

shape: (96, 13, 1), freq: MS, size: 9.75 KB

In [5]:
results.get_feature_values(horizon=1)

                0      1      2      3      4  ...      8      9     10     11     12
1950-02-01  112.0  118.0  132.0  129.0  121.0  ...  136.0  119.0  104.0  118.0  115.0
1950-03-01  118.0  132.0  129.0  121.0  135.0  ...  119.0  104.0  118.0  115.0  126.0
1950-04-01  132.0  129.0  121.0  135.0  148.0  ...  104.0  118.0  115.0  126.0  141.0
1950-05-01  129.0  121.0  135.0  148.0  148.0  ...  118.0  115.0  126.0  141.0  135.0
1950-06-01  121.0  135.0  148.0  148.0  136.0  ...  115.0  126.0  141.0  135.0  125.0
...           ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
1957-09-01  405.0  355.0  306.0  271.0  306.0  ...  348.0  355.0  422.0  465.0  467.0
1957-10-01  355.0  306.0  271.0  306.0  315.0  ...  355.0  422.0  465.0  467.0  404.0
1957-11-01  306.0  271.0  306.0  315.0  301.0  ...  422.0  465.0  467.0  404.0  347.0
1957-12-01  271.0  306.0  315.0  301.0  356.0  ...  465.0  467.0  404.0  347.0  305.0
1958-01-01  306.0  315.0  301.0  356.0  348.0  ...  467.0  404.0  347.0  305.0  336.0

shape: (96, 13, 1), freq: MS, size: 4.88 KB